### ISSUE TITLE
Guidance phrased as personal opinion

### ISSUE THREAD

**Issue by andyw8** [betterspecs/betterspecs#142]
BetterSpecs seems to be intended as a community effort, but many the explanations use the word 'I' since the were originally written by @andreareginato.

I believe this discourages others from contributing updates advice. I would suggest taking an approach similar to the [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide), where the guidance is intended to capture the community's collective viewpoint, so is written from a non-personal point of view.

**Comment by onebree** [comment]
@andyw8 I included your suggestion in a recent todo list. I agree that any guide should be written in a commanding way (second person?). As you noted, Andrea originally wrote many of the guidelines. I do not feel, however, that his use of first-person is the reason why people do not contribute. I think people do not contribute much because PRs and issues have been stales for quite some time. (I have tried to resolve that.)

**Comment by andyw8** [comment]
Yes, I agree, it's probably not the main factor.

Regarding translations, there's probably another question there about to keep the different versions 'in sync'.

**Comment by onebree** [comment]
We are working together on figuring how to keep translations "in sync" with the English pages. If you have any ideas, do let us know.

**Comment by akz92** [comment]
I noticed this a few days ago too and I agree that it doesn't look great. Please feel free to change those phrasings, closing for now.
