### ISSUE TITLE
Old Content

### ISSUE THREAD

**Issue by kbrock** [betterspecs/betterspecs#203]
I think the http://beterspecs.org site has old content.

The `gh-pages` branch references `FactoryBot`.
`master` still references `FactoryGirl`. (but I think this is not a branch that is used)

When I go to http://betterspecs.org it still says `FactoryGirl`.

Not sure if there is something special that needs to be done to release the newer content.
Let me know if I can help in any way.

Thanks for the great resource

**Comment by akz92** [comment]
Hi @kbrock, yes this is something that we're working on. `http://betterspecs.org` mirrors the `master` branch because that's currently the only working branch. `gh-pages` is a work in progress but it's closer than ever to being ready.

The only thing missing on the `gh-pages` branch is moving the texts from each languages' `index.html` to their own `_i18n/*.yml` translation file. I'll open an issue later addressing this and asking for help from people that speak each of the languages pending.

Thanks for the feedback and your help will be much appreciated as we move towards a more active maintenance of the project! 🚀
